[options]
Architecture = aarch64
HoldPkg = pacman glibc
ParallelDownloads = 5
DisableDownloadTimeout
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = %ARCHLINUX_MIRROR%/core

[extra]
Server = %ARCHLINUX_MIRROR%/extra

[alarm]
Server = %ARCHLINUX_MIRROR%/alarm
