#!/usr/bin/env python3
"""Make the Proxmox installer initramfs consume Ventoy's ISO mapping."""

from __future__ import annotations

import pathlib
import sys


VENTOY_MARKER = "# Surface Ventoy ISO hook (generated by the ISO builder).\n"
VENTOY_END = "# End Surface Ventoy ISO hook.\n"
ISO_MOUNT_MARKER = "        # Surface Ventoy ISO mount helper (generated by the ISO builder).\n"
VENTOY_BLOCK = VENTOY_MARKER + r'''# Ventoy injects this directory into the initramfs before handing control to
# the distribution's real init.  Its Proxmox hook normally edits an older
# /sys/block/hd* scanner; current Proxmox init scripts use /sys/class/block
# instead, so that edit is a no-op.  Run the same official hook explicitly so
# Ventoy can turn the selected ISO file into /dev/mapper/ventoy.
surface_ventoy_prepare_dm() {
    if [ ! -r /ventoy/hook/debian/pve-disk.sh ] ||
       [ ! -x /ventoy/busybox/sh ] ||
       [ ! -r /ventoy/ventoy_os_param ]; then
        return 0
    fi

    # dmsetup needs its control node when this initramfs is using mdev rather
    # than udev.  The device-mapper module was loaded by the Surface LVM block
    # immediately above, so only the major/minor lookup is needed here.
    mkdir -p /dev/mapper
    if [ ! -e /dev/mapper/control ]; then
        surface_dm_major=$(sed -n 's/^ *\([0-9][0-9]*\) \+misc$/\1/p' /proc/devices)
        surface_dm_minor=$(sed -n 's/^ *\([0-9][0-9]*\) \+device-mapper$/\1/p' /proc/misc)
        if [ -n "$surface_dm_major" ] && [ -n "$surface_dm_minor" ]; then
            mknod -m 600 /dev/mapper/control c "$surface_dm_major" "$surface_dm_minor"
        fi
    fi

    echo "surface-initramfs: asking Ventoy to expose the selected ISO"
    if ! /ventoy/busybox/sh /ventoy/hook/debian/pve-disk.sh; then
        echo "[WARN] Ventoy ISO mapping hook failed; continuing with block scan"
    fi
    /sbin/mdev -s
}
surface_ventoy_prepare_dm
''' + VENTOY_END
ISO_MOUNT_HELPER = ISO_MOUNT_MARKER + r'''        surface_try_iso_mount() {
            surface_iso_loop=
            # BusyBox mount only allocates a loop device for regular files.  A
            # Ventoy virtual disk is a block device, so explicitly attach one
            # before falling back to the normal direct mount.  A loop device
            # presents 512-byte sectors even when the USB reports 4096 bytes.
            if mount -t iso9660 -o loop,ro "$1" /mnt >/dev/null 2>/tmp/iso-mount.err; then
                return 0
            fi
            if [ -x /sbin/losetup ]; then
                surface_iso_loop="$(/sbin/losetup -f 2>/dev/null || true)"
                if [ -n "$surface_iso_loop" ] &&
                   /sbin/losetup -r "$surface_iso_loop" "$1" >/dev/null 2>&1 &&
                   mount -t iso9660 -o ro "$surface_iso_loop" /mnt >/dev/null 2>/tmp/iso-mount.err; then
                    return 0
                fi
                if [ -n "$surface_iso_loop" ]; then
                    /sbin/losetup -d "$surface_iso_loop" >/dev/null 2>&1 || true
                    surface_iso_loop=
                fi
            fi
            mount -t iso9660 -o ro "$1" /mnt >/dev/null 2>/tmp/iso-mount.err
        }

'''


def replace_once(text: str, old: str, new: str) -> str:
    if text.count(old) == 1:
        return text.replace(old, new, 1)
    if text.count(old) == 0 and text.count(new) == 1:
        return text
    raise ValueError(f"cannot safely patch installer init at {old!r}")


def patch_init(text: str) -> str:
    if "Proxmox Server Solutions" not in text:
        raise ValueError("not a Proxmox installer init")

    # The LVM patch leaves this marker immediately before the stock iSCSI/ISO
    # storage scan.  Keep the Ventoy hook after dm_mod is active and before any
    # ISO device is tested.
    anchor = "# we have no iscsi daemon, so we need to scan iscsi device manually."
    if VENTOY_MARKER in text:
        start = text.index(VENTOY_MARKER)
        end = text.index(VENTOY_END, start) + len(VENTOY_END)
        text = text[:start] + text[end:]
    text = replace_once(text, anchor, VENTOY_BLOCK + anchor)

    old_glob = (
        "for i in /sys/class/block/sd* /sys/class/block/sr* /sys/class/block/scd* "
        "/sys/class/block/nvme* /sys/class/block/mmcblk*; do"
    )
    new_glob = (
        "for i in /sys/class/block/sd* /sys/class/block/sr* /sys/class/block/scd* "
        "/sys/class/block/nvme* /sys/class/block/mmcblk* /sys/class/block/dm-* "
        "/sys/class/block/loop*; do"
    )
    text = replace_once(text, old_glob, new_glob)
    delay_anchor = (
        "        delay=1 # start out with a relatively short delay, often devices get ready quite quickly\n"
    )
    if ISO_MOUNT_MARKER not in text:
        text = replace_once(text, delay_anchor, ISO_MOUNT_HELPER + delay_anchor)
    text = replace_once(
        text,
        '                    size="$(cat "$i/size")"\n',
        '                    size="$(cat "$i/size" 2>/dev/null || echo 0)"\n'
        '                    virtual_block=0\n'
        '                    case "$basedev" in\n'
        '                        dm-*|loop*) virtual_block=1 ;;\n'
        '                    esac\n',
    )
    text = replace_once(
        text,
        '                    if [ "$removable" = 1 ] ||\n',
        '                    if [ "$removable" = 1 ] || [ "$virtual_block" = 1 ] ||\n',
    )
    text = replace_once(
        text,
        '                        if mount -t iso9660 -o ro "$path" /mnt >/dev/null 2>/tmp/iso-mount.err; then\n',
        '                        if surface_try_iso_mount "$path"; then\n',
    )
    text = replace_once(
        text,
        '                                cdrom=$path\n',
        '                                cdrom="${surface_iso_loop:-$path}"\n',
    )
    scanner_cleanup = (
        '                            /sbin/losetup -d "$surface_iso_loop" >/dev/null 2>&1 || true\n'
    )
    if scanner_cleanup not in text:
        text = replace_once(
            text,
            '                            umount /mnt\n',
            '                            umount /mnt\n'
            '                            if [ -n "$surface_iso_loop" ]; then\n'
            '                                /sbin/losetup -d "$surface_iso_loop" >/dev/null 2>&1 || true\n'
            '                                surface_iso_loop=\n'
            '                            fi\n',
        )
    text = replace_once(
        text,
        '                        echo "  removable: $(cat "$i/removable"), size: $size, blkid: $(blkid "$path")";\n',
        '                        echo "  removable: $removable, size: $size, blkid: $(blkid "$path" 2>/dev/null || true)";\n',
    )
    return text


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} PROXMOX-INIT")
    path = pathlib.Path(sys.argv[1])
    patched = patch_init(path.read_text(encoding="utf-8"))
    path.write_text(patched, encoding="utf-8")


if __name__ == "__main__":
    main()
