#!/usr/bin/env python3
"""Make the Proxmox target use NetworkManager for Surface Wi-Fi."""

from __future__ import annotations

import pathlib
import sys


WIFI_MARKER = "        # Surface NetworkManager Wi-Fi setup (generated by the ISO builder).\n"

LOOP = """        foreach my $iface (sort keys $interfaces->%*) {
            my $if = $interfaces->{$iface};
            my $name = defined($netif_pin_map) ? $netif_pin_map->{ $if->{mac} } : $if->{name};

            next if $name eq $ethdev;

            $ifaces .= "\\niface $name $ntype manual\\n";
        }
"""

LOOP_PATCHED = """        foreach my $iface (sort keys $interfaces->%*) {
            my $if = $interfaces->{$iface};
            my $name = defined($netif_pin_map) ? $netif_pin_map->{ $if->{mac} } : $if->{name};

            next if $name eq $ethdev;
            # Surface Wi-Fi is managed by NetworkManager/nmcli.  Do not emit
            # an ifupdown stanza: NetworkManager's ifupdown plugin would then
            # mark wlan* unmanaged and nmcli could not activate it.
            next if $name =~ /^wl/;

            $ifaces .= "\\niface $name $ntype manual\\n";
        }

"""

NETWORK_MANAGER_CONFIG = r'''        # Keep Proxmox bridges under ifupdown2 while exposing the Surface
        # Wi-Fi interface to NetworkManager and nmcli.
        mkdir "$targetdir/etc/NetworkManager", 0755 unless -d "$targetdir/etc/NetworkManager";
        mkdir "$targetdir/etc/NetworkManager/conf.d", 0755 unless -d "$targetdir/etc/NetworkManager/conf.d";
        file_write_all(
            "$targetdir/etc/NetworkManager/conf.d/10-surface-wifi.conf",
            "[main]\nplugins=keyfile,ifupdown\n\n[ifupdown]\nmanaged=false\n\n[device-surface-wifi]\nmatch-device=interface-name:wlan*\nmanaged=true\n",
        );
        mkdir "$targetdir/etc/systemd/system/multi-user.target.wants", 0755
            unless -d "$targetdir/etc/systemd/system/multi-user.target.wants";
        unlink "$targetdir/etc/systemd/system/multi-user.target.wants/NetworkManager.service";
        symlink(
            "/lib/systemd/system/NetworkManager.service",
            "$targetdir/etc/systemd/system/multi-user.target.wants/NetworkManager.service",
        );
'''

INSTALL_INTERFACES = '        file_write_all("$targetdir/etc/network/interfaces", $ifaces);\n'


def replace_once(text: str, old: str, new: str) -> str:
    if text.count(old) == 1:
        return text.replace(old, new, 1)
    if text.count(old) == 0 and text.count(new) == 1:
        return text
    raise ValueError(f"cannot safely patch installer module at {old!r}")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} INSTALL-PERL-MODULE")

    path = pathlib.Path(sys.argv[1])
    text = path.read_text(encoding="utf-8")
    if "package Proxmox::Install;" not in text:
        raise SystemExit(f"not a Proxmox installer module: {path}")

    text = replace_once(text, LOOP, LOOP_PATCHED)
    if WIFI_MARKER not in text:
        text = replace_once(text, INSTALL_INTERFACES, INSTALL_INTERFACES + WIFI_MARKER + NETWORK_MANAGER_CONFIG)

    if "match-device=interface-name:wlan*" not in text:
        raise SystemExit("NetworkManager Wi-Fi config was not installed")
    if "next if $name =~ /^wl/;" not in text:
        raise SystemExit("installer still emits an ifupdown stanza for Surface Wi-Fi")
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
