#!/usr/bin/env python3
"""Install the Surface EFI fallback in the ISO's actual Proxmox installer."""

from __future__ import annotations

import argparse
import pathlib


MODULE = "Proxmox::Install::SurfaceEFI"
OVERLAY_MARKER = "    # Surface EFI installer overlay (generated by the ISO builder).\n"
OVERLAY_END = "    # End Surface EFI installer overlay.\n"
EARLY_EFIVARS = '''if [ -d /sys/firmware/efi ]; then
    echo "EFI boot mode detected, mounting efivars filesystem"
    mount -nt efivarfs efivarfs /sys/firmware/efi/efivars
fi
'''
EARLY_EFIVARS_WARNING = '''if [ -d /sys/firmware/efi ]; then
    echo "EFI boot mode detected, mounting efivars filesystem"
    if ! mount -nt efivarfs efivarfs /sys/firmware/efi/efivars; then
        echo "[WARN] efivarfs is unavailable; continuing without EFI variable access"
    fi
fi
'''
OVERLAY = OVERLAY_MARKER + '''    echo "installing Surface EFI variable fallback"
    surface_perl_dir=/mnt/.installer-mp/usr/share/perl5/Proxmox
    if ! mkdir -p "$surface_perl_dir/Install" ||
       ! cp /surface-installer/Install.pm "$surface_perl_dir/Install.pm" ||
       ! cp /surface-installer/SurfaceEFI.pm "$surface_perl_dir/Install/SurfaceEFI.pm"; then
        debugsh_err_reboot "unable to install Surface EFI variable fallback"
    fi
    echo "installing Surface installer PID 1 supervisor"
    mkdir -p /mnt/.installer-mp/surface-installer
    cp /surface-installer/busybox /mnt/.installer-mp/surface-installer/busybox || debugsh_err_reboot "cannot install static BusyBox"
    cp /surface-installer/init /mnt/.installer-mp/surface-installer/init || debugsh_err_reboot "cannot install PID 1 supervisor"
    chmod 0755 /mnt/.installer-mp/surface-installer/busybox /mnt/.installer-mp/surface-installer/init
    # Keep the live helper current when rebuilding an older Surface ISO.
    if [ -x /mnt/.installer-mp/usr/sbin/NetworkManager ]; then
        mkdir -p /mnt/.installer-mp/usr/local/sbin
        cp /surface-installer/wifi-start /mnt/.installer-mp/usr/local/sbin/surface-wifi-start || debugsh_err_reboot "cannot install Wi-Fi startup helper"
        chmod 0755 /mnt/.installer-mp/usr/local/sbin/surface-wifi-start
    fi
    echo "installing Surface installer power controls"
    for surface_power_command in poweroff reboot halt; do
        rm -f "/mnt/.installer-mp/sbin/$surface_power_command"
        if ! cp /surface-installer/powerctl "/mnt/.installer-mp/sbin/$surface_power_command"; then
            debugsh_err_reboot "unable to install Surface $surface_power_command command"
        fi
        chmod 0755 "/mnt/.installer-mp/sbin/$surface_power_command"
    done
''' + OVERLAY_END


def replace_once(text: str, old: str, new: str) -> str:
    if text.count(old) == 1:
        return text.replace(old, new, 1)
    if text.count(old) == 0 and text.count(new) == 1:
        return text
    raise ValueError(f"cannot safely patch installer at {old!r}")


def patch_installer(text: str) -> str:
    text = replace_once(text, "use Proxmox::Install::RunEnv;\n",
                        f"use Proxmox::Install::RunEnv;\nuse {MODULE};\n") if f"use {MODULE};" not in text else text
    mount = '''        if ($run_env->{boot_type} eq 'efi') {
            syscmd("mount -n -t efivarfs efivarfs $targetdir/sys/firmware/efi/efivars") == 0
                || die "unable to mount efivarfs on $targetdir/sys/firmware/efi/efivars: $!\\n";
        }
'''
    text = replace_once(text, mount, f"        {MODULE}::mount_efivars($targetdir, $run_env);\n")
    target = "        my $grub_target = $run_env->{arch} eq 'arm64' ? 'arm64-efi' : 'x86_64-efi';\n"
    if f"my $surface_efi_opts = {MODULE}::grub_options();" not in text:
        text = replace_once(text, target, target + f"        my $surface_efi_opts = {MODULE}::grub_options();\n")
    text = replace_once(text, "grub-install --target $grub_target --no-floppy",
                        "grub-install --target $grub_target $surface_efi_opts --no-floppy")
    debconfig = '        $grub_debconfig .= "$grub_efi_pkg grub2/force_efi_extra_removable boolean true\\n";\n'
    if f"{MODULE}::grub_debconfig($grub_efi_pkg)" not in text:
        text = replace_once(text, debconfig, debconfig + f"        $grub_debconfig .= {MODULE}::grub_debconfig($grub_efi_pkg);\n")
    text = replace_once(text, '    syscmd("umount $targetdir/sys/firmware/efi/efivars");',
                        f"    {MODULE}::unmount_efivars($targetdir);")
    return text


def patch_init(text: str) -> str:
    if "Proxmox Server Solutions" not in text:
        raise ValueError("not a Proxmox installer init")
    text = replace_once(text, EARLY_EFIVARS, EARLY_EFIVARS_WARNING)
    if OVERLAY_MARKER in text:
        start = text.index(OVERLAY_MARKER)
        end = text.index(OVERLAY_END, start) + len(OVERLAY_END)
        if text[end:end + 1] == "\n":
            end += 1
        text = text[:start] + text[end:]
    anchor = '    if [ -x "/mnt/.installer-mp/sbin/unconfigured.sh" ]; then\n'
    old = '/bin/setsid /bin/sh -c "exec /sbin/unconfigured.sh </dev/$console >/dev/$console 2>&1"'
    new = '/surface-installer/busybox sh /surface-installer/init'
    text = replace_once(text, old, new)
    return replace_once(text, anchor, OVERLAY + "\n" + anchor)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("installer", type=pathlib.Path)
    parser.add_argument("init", type=pathlib.Path)
    args = parser.parse_args()
    # Validate both before changing either file.
    installer = patch_installer(args.installer.read_text())
    init = patch_init(args.init.read_text())
    args.installer.write_text(installer)
    args.init.write_text(init)


if __name__ == "__main__":
    main()
